Improve WorkmateListFragmentViewModel
Tgarfr/Projet-7-Go4Lunch pull request #19
Opened 2023-06-07 14:05 UTC by Tgarfr

2023-06-10 18:13 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
Cette méthode devrait être privée

2023-06-10 18:22 UTC, FGuyet requested changes

2023-06-10 18:22 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        workmateRepository.getWorkmateListLiveData().observeForever(workmateListObserver);
Attention, si la liste des workmate du repository est mise à jour après un filtre, le filtre n'a plus effet avec cette solution.

2023-06-10 18:22 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
Par convention, un getter (méthode commençant par get) devrait retourner une valeur.

2023-06-10 18:22 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
Je te propose de renommer cette méthode en `List<WorkmateListItem> convertToWorkmateListItems(List<Workmate> workmateList)`

et de faire de modifier le premier observer, pour que ce ne soit pas juste l'appel à cette méthode.

2023-06-10 18:32 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        workmateRepository.getWorkmateListLiveData().observeForever(workmateListObserver);
si `getWorkmateListResearchedFromString(string)`, il faudrait l'extraire du repository pour faire, dans ce VM, par exemple (en pseudo kotlin) : 

```kotlin

val workmateItems = MutableLiveData()

val workmateListObserver = { workmates: List<Workmate> -> 
    val filteredWorkmates = filterByName(workmates, searchLiveData.value)
    workmateItems.value = convertToWorkmateItems(filteredWorkmates)    
}

val searchObserver = { name: String -> 
    val filteredWorkmates = filterByName(workmatesLiveData.value, name)
    workmateItems.value = convertToWorkmateItems(filteredWorkmates)    
}

fun filterByName(workmates : List<Workmate>?, name: String?) {
   // Logique à déplacer du répository au VM
}

```

2023-06-10 18:34 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
Oui :)

2023-06-10 18:39 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        workmateRepository.getWorkmateListLiveData().observeForever(workmateListObserver);
Séparer en plusieurs méthodes qui prennent des paramètres et retournent des valeurs permet de les combiner facilement et les réutiliser dans plusieurs cas.

2023-06-10 19:13 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        workmateRepository.getWorkmateListLiveData().observeForever(workmateListObserver);
Bien vu

2023-06-10 19:17 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
Ok

2023-06-10 19:22 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
https://github.com/Tgarfr/Projet-7-Go4Lunch/pull/19/commits/227a393dadf2c925e3a118ac68bbbbe6a89ff9dc

2023-06-10 19:22 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        workmateRepository.getWorkmateListLiveData().observeForever(workmateListObserver);
https://github.com/Tgarfr/Projet-7-Go4Lunch/pull/19/commits/227a393dadf2c925e3a118ac68bbbbe6a89ff9dc

2023-06-10 19:23 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +    public void getWorkmateListItemList(@Nullable List<Workmate> workmateList) {
https://github.com/Tgarfr/Projet-7-Go4Lunch/pull/19/commits/227a393dadf2c925e3a118ac68bbbbe6a89ff9dc

2023-06-11 10:52 UTC, FGuyet requested changes

2023-06-11 10:52 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +            return workmateRepository.getWorkmateListResearchedFromString(searchString);
Pour être vraiment parfait, il faudrait déplacer l'implémentation de getWorkmateListResearchedFromString() du répo à ici, en utilisant workmateList passé en argument de la méthode au lieu de         `List<Workmate> workmateList = workmateListLiveData.getValue();`

2023-06-11 11:48 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +            return workmateRepository.getWorkmateListResearchedFromString(searchString);
ab86346dcb59b6a4b90b06318863871d0ca4a590

2023-06-12 08:47 UTC, FGuyet approved these changes

2023-06-12 15:59 UTC, merged