Workmate list
Tgarfr/Projet-7-Go4Lunch pull request #5
Opened 2023-04-02 13:31 UTC by Tgarfr

Add workmate list

2023-04-02 16:28 UTC, FGuyet requested changes

2023-04-02 16:28 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateFragment.java
> +        firestoreRecyclerAdapter = new WorkmateListAdapter(firestoreRecyclerOptions, viewModel.getRestaurantRepository() ,getContext());
Attention, passer un Repository à un adaptateur ne correspond pas à l'architecture MVVM. 

D'ailleurs, un ViewModel n'expose jamais les Repositories qu'il utilise, il abstrait cela pour la vue.

2023-04-02 16:28 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateFragment.java
> +        firestoreRecyclerAdapter = new WorkmateListAdapter(firestoreRecyclerOptions, viewModel.getRestaurantRepository() ,getContext());
Il faudra donc que le viewModel expose un liveData de restaurants. Le fragment observera cette source et mettra à jour l'adapteur.

2023-04-02 16:28 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateFragmentViewModel.java
> +    public Query getWorkmateListQuery() {
Pas besoin d'exposer la query aux fragment

2023-04-02 16:28 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateFragmentViewModel.java
> +    public RestaurantRepository getRestaurantRepository() {
Il ne faut pas exposer les repositories. Exposer les données via LiveData

2023-04-02 16:28 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListAdapter.java
> +                holder.workmateText.setText(workmate.getName()+" is eating "+restaurant.getType()+" ( "+restaurant.getName()+" ) ");
Cela peut se régler dans une prochaine MR, mais il faudra gérer les traductions et passer par des resources string avec arguments.

2023-04-03 12:38 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateFragment.java
> +        firestoreRecyclerAdapter = new WorkmateListAdapter(firestoreRecyclerOptions, viewModel.getRestaurantRepository() ,getContext());
Tu a raison. :)
Mais la j'ai besoin d'acceder à la methode getRestaurantFromId, pas à la liste livedata.
Mais je pense pas que mettre cette methode dans l'adapteur serait pertinant.
Est ce qu'il faut que mon adapteur est accés au viewmodel, c'est plus correct ?

2023-04-03 13:14 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListAdapter.java
> +                holder.workmateText.setText(workmate.getName()+" is eating "+restaurant.getType()+" ( "+restaurant.getName()+" ) ");
getRessource n'est pas accessible depuis l'adapteur. mais je peut lui donner.

De ce que j'ai compris il faudrait utiliser la methodes String.Format (..... (variable) ...);
Est ce que ce texte pourait être générer dans le view model ? Quel est la bonne pratique ?

2023-04-06 08:43 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        List<DocumentSnapshot> documentsList = workmateDocumentSnapshotListLiveData.getValue();
La notion de DocumentSnapshot ne devrait pas sortir du repository car c'est une notion propre à ta source de donnée (FireStore). Tes ViewModel devraient récupérer la liste de Workmate directement.

2023-04-06 08:47 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListAdapter.java
> +            Restaurant restaurant = restaurantRepository.getRestaurantFromId(workmate.getRestaurantUid());
Pas de repository dans l'adapteur. SI tu as besoin du restaurant (et pas que son ID), passer tout l'objet dans le WorkmateListItem

2023-04-06 09:42 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListAdapter.java
> +            Restaurant restaurant = restaurantRepository.getRestaurantFromId(workmate.getRestaurantUid());
J'ai voulu aller un peu trop vite hier, j'y ai amené la donné formaté en oubliant d'enlevé le répository. :)

2023-04-06 09:47 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        List<DocumentSnapshot> documentsList = workmateDocumentSnapshotListLiveData.getValue();
Ok c'est ce que j'ai essayé de te demandé hier, je vais créer un Workmate Api pour que le repository ne gére pas Firestore.

2023-04-08 12:34 UTC, FGuyet commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        List<DocumentSnapshot> documentsList = workmateDocumentSnapshotListLiveData.getValue();
Ok désolé alors je n'avais pas compris !

2023-04-08 12:38 UTC, FGuyet approved these changes

2023-04-08 14:26 UTC, Tgarfr commented on app/src/main/java/com/startup/go4lunch/ui/WorkmateListFragmentViewModel.java
> +        List<DocumentSnapshot> documentsList = workmateDocumentSnapshotListLiveData.getValue();
;)

2023-04-13 16:15 UTC, FGuyet commented
N'oublie pas de merger :)

2023-04-14 07:38 UTC, Tgarfr commented
> N'oublie pas de merger :)

J'avais pas vu que tu l'avais validé :) Super si c'est Ok :)

2023-04-14 07:39 UTC, merged